Update build.yml *NOBUILD*
testing a way to cancel building

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,6 +23,12 @@ jobs:
           echo EOF >> $env:GITHUB_ENV
           echo "Commit Title: $COMMIT_TITLE"
           echo "Commit Description: $COMMIT_DESCRIPTION"
+      - name: Check Commit Title
+        run: |
+          if echo "${COMMIT_TITLE}" | grep -q "*NOBUILD*"; then
+            echo "Commit title contains *NOBUILD*. Cancelling workflow."
+            exit 78  # You can choose a different exit code if needed
+          fi
       - name: Install Python
         uses: actions/setup-python@v1
         with:
